package com.vibe.app.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "REMINDER".
 */
public class Reminder {

    private Long _id;
    private String name;
    private Integer flag;
    private Integer hour;
    private Integer minute;
    private Integer week;
    private String tips;
    private Integer soundOrVibrator;
    private Integer state;

    public Reminder() {
    }

    public Reminder(Long _id) {
        this._id = _id;
    }

    public Reminder(Long _id, String name, Integer flag, Integer hour, Integer minute, Integer week, String tips, Integer soundOrVibrator, Integer state) {
        this._id = _id;
        this.name = name;
        this.flag = flag;
        this.hour = hour;
        this.minute = minute;
        this.week = week;
        this.tips = tips;
        this.soundOrVibrator = soundOrVibrator;
        this.state = state;
    }

    public Reminder(String name, Integer flag, Integer hour, Integer minute, Integer week, String tips, Integer soundOrVibrator, Integer state) {
        this.name = name;
        this.flag = flag;
        this.hour = hour;
        this.minute = minute;
        this.week = week;
        this.tips = tips;
        this.soundOrVibrator = soundOrVibrator;
        this.state = state;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    public Integer getHour() {
        return hour;
    }

    public void setHour(Integer hour) {
        this.hour = hour;
    }

    public Integer getMinute() {
        return minute;
    }

    public void setMinute(Integer minute) {
        this.minute = minute;
    }

    public Integer getWeek() {
        return week;
    }

    public void setWeek(Integer week) {
        this.week = week;
    }

    public String getTips() {
        return tips;
    }

    public void setTips(String tips) {
        this.tips = tips;
    }

    public Integer getSoundOrVibrator() {
        return soundOrVibrator;
    }

    public void setSoundOrVibrator(Integer soundOrVibrator) {
        this.soundOrVibrator = soundOrVibrator;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

}
